version: "3"

services:
    mongo:
        container_name: mongodb
        image: mongo
        ports: 
            - "27018:27017"
    serv:
        container_name: serv
        restart: always
        build: .
        ports: 
            - "3901:3900"
        links:
            - mongo
    
